name: MasterDeployCI

on:
  workflow_dispatch: # ← shows a green “Run workflow” button in the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.20.4]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: |
          export branch_name=main
          git fetch origin $branch_name
          git checkout $branch_name
          git pull origin $branch_name
          npm install
      - name: Deploy to GH Pages
        run: |
          git config --global user.email ${{secrets.EMAIL}}
          git config --global user.name ${{secrets.USERNAME}}
          git remote set-url origin https://${{secrets.PERSONAL_ACCESS_TOKEN}}@github.com/${{secrets.USERNAME}}/dipeshpatil.github.io.git
          export CI=false
          export REACT_APP_GITHUB_TOKEN=${{secrets.PERSONAL_ACCESS_TOKEN}}
          export GITHUB_USERNAME=${{secrets.USERNAME}}
          export USE_GITHUB_DATA=true
          npm run deploy
