name: MasterDeployCI
on:
  push:
    branches:
      - in-dev
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      - name: Deploy to GH Pages
        run: |
          git config --global user.email ${{secrets.EMAIL}}
          git config --global user.name ${{secrets.USERNAME}}
          git remote set-url origin https://${{secrets.PERSONAL_ACCESS_TOKEN}}@github.com/${{secrets.USERNAME}}/dipeshpatil.github.io.git
          export REACT_APP_GITHUB_TOKEN=${{secrets.PERSONAL_ACCESS_TOKEN}}
          export GITHUB_USERNAME=${{secrets.USERNAME}}
          export USE_GITHUB_DATA=true
          npm run deploy
